---
name: RPM build
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Submit a build from Fedora container
    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make

      - name: Build the source RPM
        run: |
          make rpm-src

      - name: Submit the build by uploading the source RPM
        run: |
          make rpm-copr
